game_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('product.urls', namespace='game'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views


app_name = "game"
urlpatterns = [
   path("", views.index, name="index"),
   path('game_detail/<int:id>/',views.game_detail,name='game_detail'),
   path('contact_us/',views.contact_us,name='contact_us'),
   path('games/', views.game_list, name='game-list'),
   path('filter_games/', views.filter_games, name='filter_games'),
   path('trending_games/', views.trending_game, name='trending_games'),
   path('most_played/', views.most_played_game, name='most_played'),
   path('login/', views.user_login, name='login'),
   path('logout/', views.user_logout, name='logout'),
   path('register/', views.user_register, name='register'),
   path('profile/', views.profile, name='profile'),
   path('search/', views.game_search, name='search'),
   path('password_change', views.password_change, name='password_change'),
   path('password_change_done', views.password_change_done, name='password_change_done'),
   path('reset_password', views.reset_password, name='reset_password'),
   path('reset_password_done', views.reset_password_done, name='reset_password_done'),
   path('add_to_cart/<int:game_id>/', views.add_to_cart, name="add_to_cart"),
   path('cart/', views.cart_printer, name="cart"),
   path('update_quantity/', views.update_quantity, name="update_quantity"),
   path('remove_game/', views.remove_game, name="remove_game"),
   path('picture_change/', views.picture_change, name="picture_change"),
   path('order/', views.order, name="order"),
]

product/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField


class CustomUser(AbstractUser):
    image = ResizedImageField(size=[150, 150], crop=['middle', 'center'], quality=85, upload_to='images/profiles',null=True, blank=True)
    email = models.EmailField(unique=True)
    address = models.TextField(default='', null=True, blank=True)
    phone = models.CharField(default='', max_length=11, unique=True)


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    title = models.CharField(max_length=100)
    summary = models.TextField(help_text="write a summary of the game story", null=True, blank=True)
    price = models.IntegerField(default=0)
    sold_count = models.IntegerField(default=0)
    off = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100), MinValueValidator(0)])
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='games', null=True, blank=True)
    image = models.ImageField(upload_to="images/games")
    tags = TaggableManager()
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [models.Index(fields=['-created_at', '-off'])]
        verbose_name = 'Game'
        verbose_name_plural = 'Games'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("game:game_detail", args=[self.id])

    def get_final_price(self):
        return self.price - ((self.price * self.off) // 100)





class Ticket(models.Model):
    class Status(models.TextChoices):
        LOGIN = 'Login & Logout Error', 'Login & Logout Error'
        BUY = 'Buying Error', 'Buying Error'
        OTHER = 'Other', 'Other'

    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=50, choices=Status.choices)
    message = models.TextField()

    def __str__(self):
        return self.name


class Order(models.Model):
    buyer = models.ForeignKey(CustomUser, related_name="orders", on_delete=models.SET_NULL, null=True)
    postal_code = models.CharField(max_length=10)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [models.Index(fields=['-created'])]

    def __str__(self):
        return f"order {self.id}"

    def get_total_cost(self):
        return sum(item.cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    game = models.ForeignKey(Game, related_name="order_items", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{str(self.id)} : {self.game.title}"

    def cost(self):
        return self.game.get_final_price() * self.quantity

product/views.py
from urllib.parse import quote
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.decorators.http import require_POST
from .models import Game, Category, CustomUser, OrderItem
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse
from django.template.loader import render_to_string
from .forms import *
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import TrigramSimilarity
from itsdangerous import URLSafeTimedSerializer, BadSignature, SignatureExpired
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from decouple import config
from .cart import Cart
import uuid
from django.views.decorators.cache import cache_page
from django.core.cache import cache


def index(request):
    games = Game.objects.all()
    best_offer = games.order_by('-off').first()
    trending_games = games.order_by('-created_at')[:4]
    most_played = games.order_by('-sold_count')[:6]
    context = {"best_offer": best_offer, "trending_games": trending_games, "most_played": most_played}
    return render(request, "product/index.html", context)


def game_detail(request, id):
    cache_key = f'game_detail_{id}'
    game = cache.get(cache_key)
    if not game:
        game = get_object_or_404(Game, id=id)
        cache.set(cache_key, game, timeout=60 * 30)
    similar_games = Game.objects.filter(category_id=game.category).exclude(id=game.id)[:5]
    return render(request, "product/product-details.html", {"game": game, "similar_games": similar_games})


def contact_us(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Ticket sent successfully!")
            return redirect('game:contact_us')
    else:
        form = TicketForm()
    return render(request, "product/contact.html", {"form": form})


@cache_page(60 * 30,key_prefix='game_list')
def game_list(request):
    games = Game.objects.all()
    categories = Category.objects.all()
    return render(request, "product/shop.html", {"games": games, "categories": categories})


def filter_games(request):
    category = request.GET.get('category', 'all')
    if category == 'all':
        games = Game.objects.all()
    else:
        games = Game.objects.filter(category__name=category)
    html = render_to_string('partials/game_list_items.html', {'games': games})
    return JsonResponse({'html': html})


def trending_game(request):
    games = Game.objects.all().order_by('-created_at')
    paginator = Paginator(games, 3)
    page_number = request.GET.get('page', 1)
    try:
        games = paginator.page(page_number)
    except EmptyPage:
        games = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        games = paginator.page(1)
    return render(request, 'product/trending.html', {'games': games})


def most_played_game(request):
    games = Game.objects.all().order_by('-sold_count')
    paginator = Paginator(games, 3)
    page_number = request.GET.get('page', 1)
    try:
        games = paginator.page(page_number)
    except EmptyPage:
        games = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        games = paginator.page(1)
    return render(request, 'product/most-played.html', {'games': games})


def user_login(request):
    cart_data = request.session.get('cart', {})
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    request.session['cart'] = cart_data
                    messages.success(request, "You are now logged in!")
                    return redirect('game:index')
            else:
                messages.error(request, "Invalid username or password!")
                return redirect('game:login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required(login_url='game:login')
def user_logout(request):
    logout(request)
    messages.success(request, "You have been logged out.")
    return redirect('game:index')


def user_register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            messages.success(request, f"Welcome {user.username}!")
            return redirect('game:index')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required(login_url='game:login')
def profile(request):
    user = request.user
    if request.method == "POST":
        form = UserEditForm(instance=user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your profile has been updated!")
            return redirect('game:profile')
    else:
        form = UserEditForm(instance=user)
    return render(request, 'product/profile.html', {'user': user, 'form': form})


def game_search(request):
    query = request.GET.get('query', None)
    games = []
    if query:
        games1 = Game.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gte=0.3)
        games2 = Game.objects.annotate(similarity=TrigramSimilarity('summary', query)).filter(similarity__gte=0.3)
        games = (games1 | games2).order_by('-similarity')
    return render(request, 'product/search.html', {'games': games, 'query': query})


serializer = URLSafeTimedSerializer(settings.SECRET_KEY)


def generate_token(obj):
    return serializer.dumps({'obj': obj})


def verify_token(token):
    try:
        data = serializer.loads(token, max_age=600)
        return data['obj']
    except Exception:
        return None


@login_required(login_url='game:login')
def password_change(request):
    password = request.GET.get('password', None)
    user = request.user
    if password:
        if user.check_password(password):
            token = generate_token(user.id)
            token = quote(token)
            return redirect(f"{reverse('game:password_change_done')}?token={token}")
        else:
            messages.error(request, "Invalid password!")
            return redirect('game:password_change')

    return render(request, 'registration/password_change.html')


@login_required(login_url='game:login')
def password_change_done(request):
    token = request.GET.get('token')
    if not token or verify_token(token) != request.user.id:
        return HttpResponseForbidden("Invalid or expired token!")

    user = request.user
    if request.method == 'POST':
        form = UserPasswordChangeForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            messages.success(request, "Your password has been updated!")
            return redirect('game:profile')
    else:
        form = UserPasswordChangeForm()
    return render(request, 'registration/password_change_done.html', {'form': form})


def reset_password(request):
    email = request.GET.get('email', None)
    if email:
        if CustomUser.objects.filter(email=email).exists():
            unique_id = str(uuid.uuid4())
            token = serializer.dumps({'email': email, 'unique_id': unique_id}, salt='password-reset-salt')
            token = quote(token)
            html_content = render_to_string('email/reset_password_email.html', {
                'reset_url': f"http://127.0.0.1:8000{reverse('game:reset_password_done')}?token={token}"})
            email_message = EmailMultiAlternatives(
                'reset password',
                "If you’re trying to reset your password, use the link provided in the email.",
                config("EMAIL_HOST_USER"),
                [email],
            )
            email_message.attach_alternative(html_content, "text/html")
            email_message.send()
            messages.success(request, "Email has been sent!")
            return redirect('game:login')
        else:
            messages.error(request, "Invalid email!")
            return redirect('game:reset_password')

    return render(request, 'registration/reset_password.html')


def reset_password_done(request):
    token = request.GET.get('token')
    try:
        date = serializer.loads(token, salt='password-reset-salt')
        email = date['email']
        user = CustomUser.objects.get(email=email)
    except (BadSignature, SignatureExpired):
        return HttpResponseForbidden("Invalid token!")
    if request.method == 'POST':
        form = UserPasswordChangeForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            messages.success(request, "Your password has been updated!")
            return redirect('game:login')
    else:
        form = UserPasswordChangeForm()
    return render(request, 'registration/reset_password_done.html', {'form': form, 'user': user})


@require_POST
def add_to_cart(request, game_id):
    try:
        cart = Cart(request)
        game = get_object_or_404(Game, id=game_id)
        cart.add_to_cart(game)
        context = {"sus": "Game has been added to your cart"}
        return JsonResponse(context)
    except:
        return JsonResponse({'error': 'invalid request'})


def cart_printer(request):
    cart = Cart(request)
    print(cart.cart)

product/templates/product/contact.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Contact Us{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
 <div class="page-heading header-text">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h3>Contact Us</h3>
          <span class="breadcrumb"><a href="{% url 'game:index' %}">Home</a>  >  Contact Us</span>
        </div>
      </div>
    </div>
  </div>

  <div class="contact-page section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="left-text">
            <div class="section-heading">
              <h6>Contact Us</h6>
              <h2>Say Hello!</h2>
            </div>
            <p>LUGX Gaming is the best gaming shop you could ever wish for, best prices, complete game collection and so much more! </p>
            <ul>
              <li><span>Address</span> Sunny Isles Beach, FL 33160, United States</li>
              <li><span>Phone</span>+98 9197351889</li>
              <li><span>Email</span>mohammadmahdi1121382@gmail.com</li>
            </ul>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="right-content">
            <div class="row">
              <div class="col-lg-12">
                <div id="map">
                  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12469.776493332698!2d-80.14036379941481!3d25.907788681148624!2m3!1f357.26927939317244!2f20.870722720054623!3f0!3m2!1i1024!2i768!4f35!3m3!1m2!1s0x88d9add4b4ac788f%3A0xe77469d09480fcdb!2sSunny%20Isles%20Beach!5e1!3m2!1sen!2sth!4v1642869952544!5m2!1sen!2sth" width="100%" height="325px" frameborder="0" style="border:0; border-radius: 23px;" allowfullscreen=""></iframe>
                </div>
              </div>
              <div class="col-lg-12">
                <form id="contact-form" action="" method="post">
                    {% csrf_token %}
                  <div class="row">
                    <div class="col-lg-6">
                      <fieldset>
                        {{ form.name }}
                      </fieldset>
                    </div>
                    <div class="col-lg-6">
                      <fieldset>
                          {{ form.last_name }}
                      </fieldset>
                    </div>
                    <div class="col-lg-6">
                      <fieldset>
                        {{ form.email }}
                      </fieldset>
                    </div>
                    <div class="col-lg-6">
                      <fieldset>
                        {{ form.subject }}
                      </fieldset>
                    </div>
                    <div class="col-lg-12">
                      <fieldset>
                        {{ form.message }}
                      </fieldset>
                    </div>
                    <div class="col-lg-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="orange-button">Submit a Ticket Now</button>
                        {% if messages %}
                            <div id="notification" class="notification">
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            </div>
                        {% endif %}
                      </fieldset>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<script>
    window.onload = function() {
        var notification = document.getElementById("notification");
        if (notification) {
            notification.className = "notification show";
            setTimeout(function(){ notification.className = notification.className.replace("show", ""); }, 3000);
        }
    };
</script>
{% endblock %}

product/templates/product/index.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Lugx Gaming{% endblock %}
{% block content %}
    <div class="main-banner">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="caption header-text">
            <h6>Welcome to lugx</h6>
            <h2>BEST GAMING SITE EVER!</h2>
            <p>LUGX Gaming is the best game shop ever. you can find any game you want in here with best prices and mind blowing offers, enjoy! </p>
            <div class="search-input">
              <form id="search" action="{% url 'game:search' %}">
                <input type="text" placeholder="Type Something" id='searchText' name="query" onkeypress="handle" />
                <button role="button">Search Now</button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-lg-4 offset-lg-2">
          <div class="right-image">
            <img src="{{ best_offer.image.url }}" alt="">
            <span class="price">${{ best_offer.get_final_price }}</span>
            <span class="offer">-{{ best_offer.off }}%</span>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="section trending">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="section-heading">
            <h6>Trending</h6>
            <h2>Trending Games</h2>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="main-button">
            <a href="{% url 'game:trending_games' %}">View All</a>
          </div>
        </div>
        {% for game in trending_games %}
            <div class="col-lg-3 col-md-6">
          <div class="item">
            <div class="thumb">
              <a href="{{ game.get_absolute_url }}"><img src="{{ game.image.url }}" alt=""></a>
              <span class="price">{% if game.off == 0  %}${{ game.price }}{% else %}<em>${{ game.price }}</em>${{ game.get_final_price }}{% endif %}</span>
            </div>
            <div class="down-content">
              <span class="category">{{ game.category }}</span>
              <h4>{{ game.title }}</h4>
              <a href="{{ game.get_absolute_url }}"><i class="fa fa-shopping-bag"></i></a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="section most-played">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="section-heading">
            <h6>TOP GAMES</h6>
            <h2>Most Played</h2>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="main-button">
            <a href="{% url 'game:most_played' %}">View All</a>
          </div>
        </div>
       {% for game in most_played %}
            <div class="col-lg-2 col-md-6 col-sm-6">
          <div class="item">
            <div class="thumb">
              <a href="{{ game.get_absolute_url }}"><img src="{{ game.image.url }}" alt=""></a>
            </div>
            <div class="down-content">
                <span class="category">{{ game.category }}</span>
                <h4>{{ game.title}}</h4>
                <a href="{{ game.get_absolute_url }}">Explore</a>
            </div>
          </div>
        </div>
       {% endfor %}
      </div>
    </div>
  </div>

  <div class="section cta">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          <div class="shop">
            <div class="row">
              <div class="col-lg-12">
                <div class="section-heading">
                  <h6>Our Shop</h6>
                  <h2>Go Pre-Order Buy & Get Best <em>Prices</em> For You!</h2>
                </div>
                <p>Best prices,don't miss out our offs on the greatest hits of the gaming industry!</p>
                <div class="main-button">
                  <a href="{% url 'game:game-list' %}">Shop Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-5 offset-lg-2 align-self-end">
          <div class="subscribe">
            <div class="row">
              <div class="col-lg-12">
                <div class="section-heading">
                  <h6>Dear customer</h6>
                  <h2>If there is any problem with the site please help us by submitting a <em>Ticket</em>, thanks!</h2>
                </div>
                <div class="main-button">
                    <a href="{% url 'game:contact_us' %}" class="btn-danger">Submit a ticket</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% if messages %}
    <div id="notification" class="notification">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
<script>
    window.onload = function() {
        var notification = document.getElementById("notification");
        if (notification) {
            notification.className = "notification show";
            setTimeout(function(){ notification.className = notification.className.replace("show", ""); }, 3000);
        }
    };
</script>
{% endblock %}

product/templates/product/most-played.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Most Played Games{% endblock %}
{% block content %}
    <div class="page-heading header-text">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3>Most Played Games</h3>
                    <span class="breadcrumb"><a href="{% url 'game:index' %}">Home</a> > Most Played Games </span>
                </div>
            </div>
        </div>
    </div>

    <div class="section trending">
        <div class="container">
            <div class="row trending-box" id="games-container">
                {% for game in games %}
                    <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 adv">
                        <div class="item">
                            <div class="thumb">
                                <a href="{{ game.get_absolute_url }}"><img src="{{ game.image.url }}" alt=""></a>
                                <span class="price">{% if game.off == 0 %}${{ game.price }}{% else %}
                                    <em>${{ game.price }}</em>$
                                    {{ game.get_final_price }}{% endif %}</span>
                            </div>
                            <div class="down-content">
                                <span class="category">{{ game.category }}</span>
                                <h4>{{ game.title }}</h4>
                                <a href="{{ game.get_absolute_url }}"><i class="fa fa-shopping-bag"></i></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="pagination">
                        {% if games.has_previous %}<li><a href="?page={{ games.previous_page_number}}"> &lt; </a></li>{% endif %}
                        {% for page in games.paginator.page_range %}
                        <li><a {% if games.number == page %}class="is_active"{% endif %} href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}
                        {% if games.has_next %}<li><a href="?page={{ games.next_page_number }}"> &gt; </a></li>{% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/order.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Order{% endblock %}
{% block content %}
<header class="header">
    <h1>Submit Your Details</h1>
</header>
<main class="content">
    <div class="form-card">
      <h2>{{ request.user.username }}'s Information</h2>
      <hr>
      {% if cart %}
      <form action="" method="post">
        {% csrf_token %}
        {% if form.errors %}
            <div class="error-container">
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            {{ field.label }}:{{ error }}
                            <hr>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </div>
      {% endif %}
        <div class="form-group">
            {{ form.postal_code }}
        </div>
        <div class="form-group">
            {{ form.province }}
        </div>
        <div class="form-group">
            {{ form.city }}
        </div>
        <button type="submit" class="submit-btn">Order</button>
      </form>
      {% else %}
       <p>Your cart is empty</p>
       {% endif %}
    </div>
</main>
{% endblock %}

product/templates/product/product-details.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}{{ game.title }}{% endblock %}
{% block content %}
<div class="page-heading header-text">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h3>{{ game.title }}</h3>
          <span class="breadcrumb"><a href="{% url 'game:index' %}">Home</a>  >  <a href="{% url 'game:game-list' %}">Shop</a>  >  {{ game.title }}</span>
        </div>
      </div>
    </div>
  </div>

  <div class="single-product section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="left-image">
            <img src="{{ game.image.url }}" alt="game cover">
          </div>
        </div>
        <div class="col-lg-6 align-self-center">
          <h4>{{ game.title }}</h4>
          <span class="price">{% if game.off == 0 %}${{ game.price }}{% else %}<em>${{ game.price }}</em> ${{ game.get_final_price }}{% endif %}</span>
          <p>{{ game.summary|linebreaks }}</p>
            {% if game.id|stringformat:"s" in cart.cart %}
                <p>this game is already in your cart</p>
            {% else %}
                <button id="qty" type="button"><i id="badge" class="fa fa-shopping-bag"></i> ADD TO CART</button>
            {% endif %}
          <ul>
            <li><span>Game ID:</span> {{ game.id }}</li>
            <li><span>category:</span><a href="#">{{ game.category }}</a></li>
            <li><span>Multi-tags:</span> {% for tag in game.tags.all %} <a href="#">#{{ tag }}</a>,{% endfor %}</li>
          </ul>
        </div>
        <div class="col-lg-12">
          <div class="sep"></div>
        </div>
      </div>
    </div>
  </div>


  <div class="section categories related-games">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="section-heading">
            <h2>Related Games</h2>
          </div>
        </div>
        <div class="col-lg-6">
        </div>
        {% for game in similar_games.all %}
        <div class="col-lg col-sm-6 col-xs-12">
          <div class="item">
            <h4>{{ game.category}}</h4>
            <div class="thumb">
              <a href="{{ game.get_absolute_url }}"><img src="{{ game.image.url }}" alt=""></a>
            </div>
          </div>
        </div>
        {% endfor %}
        <div class="col-lg col-sm-6 col-xs-12">
        </div>
        <div class="col-lg col-sm-6 col-xs-12">
        </div>
        <div class="col-lg col-sm-6 col-xs-12">
        </div>
        <div class="col-lg col-sm-6 col-xs-12">
        </div>
      </div>
    </div>
  </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
        $(document).ready(function () {
            $('#qty').click(function () {
                $.ajax({
                    type: 'POST',
                    url: '{% url 'game:add_to_cart' game.id %}',
                    data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    success: function (data) {
                        $('#qty').text(data.sus);
                        $('#qty').prop('disabled',true);
                    }
                });
            });
        });
</script>
{% endblock %}